name: Build

on:
  push:
    branches: [ "main"]
  workflow_dispatch:
    inputs:
      release:
        description: 'Skip pre release build'
        required: false
        type: boolean

jobs:
 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Get current version
      id: current_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_release_rules: feat:patch,bump:minor
        dry_run: true

    - name: Bump version and push tag
      if: ${{ !inputs.release }}
      id: release_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_release_rules: feat:patch,bump:minor
    
    - name: Create a GitHub release
      if: ${{ !inputs.release }}
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.release_version.outputs.new_tag }}
        name: Release ${{ steps.release_version.outputs.new_tag }}
        body: ${{ steps.release_version.outputs.changelog }}
        artifacts: "./sasesp-monitoring*.zip"
        preRelease: true
