name: Clean Up Environment

on:
  workflow_dispatch:

jobs:
  cleanUp:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
        # shallow clone doesn't fetch tags, so cdp-release-management plugin doesn't work without this
          fetch-depth: 0

      - name: Remove Monitoring Cluster via bash script
        shell: bash
        run: |
          export USER_DIR=${GITHUB_WORKSPACE}/Monitoring/customizations
          echo ${USER_DIR}/monitoring
          sed -i 's/host.mycluster.example.com/monitoring.espviya129-azure-nginx-e07a1be2.unx.sas.com/g' user-values-prom-operator.yaml
          cat user-values-prom-operator.yaml
          cd ${GITHUB_WORKSPACE}/Monitoring/viya4-monitoring-kubernetes-1.2.20/monitoring/bin 
          ls
          ./remove_monitoring_cluster.sh
          kubectl delete namespace monitoring
