name: Clean Up Environment

on:
  workflow_dispatch:

jobs:
  cleanUp:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
        # shallow clone doesn't fetch tags, so cdp-release-management plugin doesn't work without this
          fetch-depth: 0

      - name: Remove Monitoring Cluster via bash script
        shell: bash
        run: |
          cd $HOME
          mkdir .kube
          cd .kube
          echo "${{ secrets.KUBERNETES_CONFIG }}" > config
          export USER_DIR=${GITHUB_WORKSPACE}/Monitoring/customizations
          cd ${USER_DIR}/monitoring
          sed -i 's/host.mycluster.example.com/${{ secrets.K8S_CLUSTER }}/g' user-values-prom-operator.yaml
          cd ${GITHUB_WORKSPACE}/Monitoring/viya4-monitoring-kubernetes-1.2.20/monitoring/bin 
          bash remove_monitoring_cluster.sh
          kubectl delete namespace monitoring
          sleep 180s
          bash deploy_monitoring_cluster.sh
